### ISSUE TITLE
Adjust MVS Gear Pricing

### ISSUE THREAD

**Issue by BnYrB** [42MonthsAfter/42MonthsAfter-Public#441]
We need to take a look at the pricing and get more accurate with what each item costs. Right now everything has the same price by type, but we need to get this more realistic so that the price represents the benefits of the item.

Example: smaller capacity = lower value

**Comment by BnYrB** [comment]
@SargeD Do you want to take a stab at this if it wasn't already part of the updates that you pushed?

**Comment by SargeD** [comment]
Done
