### ISSUE TITLE
Car Repair Mod

### ISSUE THREAD

**Issue by SargeD** [42MonthsAfter/42MonthsAfter-Public#460]
When you repair an item that is not attached to the vehicle, when it is done repairing it spawns the new repaired item about 30 feet in the air.

**Comment by BnYrB** [comment]
This being a mod bug that we can't fix, should we drop this mod as a whole and look for a new one? Are people repairing their cars a lot?

**Comment by BnYrB** [comment]
Closing out as there hasn't been any discussion on this for a while.
