### ISSUE TITLE
JMC Security Keycard 2 & Ice Crypt Loot

### ISSUE THREAD

**Issue by Raider2-1** [42MonthsAfter/42MonthsAfter-Public#462]
We did the puzzle for the keycard and it did not spawn, we have heard people talking about the keycard having wack respawn times and such. Maybe a similar situation as Thor's Hammer?
Also the loot pools for the Ice Crypt are super underwhelming. We are finding items like CZ and KEDR mags, weapon attachments that are without their weapon counterpart and just a general lack of anything "good". We did not find any MVS gear or anything else similar. We did find 2 large rifles so the loot is not entirely screwed.
Also suggest looking at the Aircraft Carrier loot but we haven't checked that out yet.
![image](https://user-images.githubusercontent.com/83690102/170917467-da3e9d20-656e-4b60-9727-f80c06d57ca7.png)

**Comment by BnYrB** [comment]
I removed all vanilla stuff from the artic, tomb and vault, should only be the high tier stuff we looked at spawning in.

The keycard were still at stock Deer Isle values, I extended the life similar to what we did with thors hammer.

**Comment by BnYrB** [comment]
Will close for now, we can reopen if there are still issues in the future.
