### ISSUE TITLE
No ammo purchase at BM

### ISSUE THREAD

**Issue by Kingboggieman** [42MonthsAfter/42MonthsAfter-Public#464]
So me and demon went to black market yesterday night and we were not able to buy alot of the big ammo like the 50 cal or 20.102 ammo.

**Comment by BnYrB** [comment]
![Screenshot (40)](https://user-images.githubusercontent.com/8458331/172237854-f3d10980-3022-4532-9fb5-8583b12e7334.png)

Updated
