### ISSUE TITLE
Items that need to be added to the Quartermaster

### ISSUE THREAD

**Issue by SargeD** [42MonthsAfter/42MonthsAfter-Public#469]
WEAPONS

AEK
MASSAR15DMR
MASSAR15DMR_DESERT
AVS36
JMC_PROTOTYPE_BLUE
JMC_PROTOTYPE_RED
JMC_PROTOTYPE_WHITE
JMC_SNOWOWL
TTSCARL
MASSM16
TTSOK96
TTAK458
TTAK458POLI
TTAGRAM
TTP90
TTSTG44
TTRPD
FOX_HK416D
FOX_HK416D_TAN
FOX_HK416D_GREEN
FOX_HK416D_SNOW
CROSSBOW_BLACK
CROSSBOW_RED
CROSSBOW_BLUE
CROSSBOW_GREEN
CROSSBOW_LEAVES
MASSTMP153

MAGAZINES

JMC_PROTOTYPE_MAG
JMC_SNOWOWL_MAG
FOX_MAG_FN57_20RND
FOX_MAG_FN57_30RND
MASS357M1911MAG
MASS_MAG_9X39PALM_30RND

WEAPON ATTACHMENTS

UNIVERSALLIGHT - ITS IN THE TRADER BUT YOU CAN'T SELL IT
MASSSCOPE
JMC_PROTOTYPE_OPTIC_BLUE
JMC_PROTOTYPE_OPTIC_RED
JMC_PROTOTYPE_OPTIC_WHITE
JMC_SNOWOWL_OPTIC
LEUPOLD_MUNG
MASSHOLO
MASSHOLO2
MASSPKA
MASSAR15ADJBTTSTCK
MASSM417STOCK
FOX_RAMROD_BRUSH
PP19_BTTSTCK
SHOTGUN_SUPPRESSOR - ITS IN THE TRADER BUT YOU CAN'T SELL IT

GRENADES

M18SMOKEGRENADE_RED
M18SMOKEGRENADE_RED_CONTAMINATED
M18SMOKEGRENADE_GREEN
M18SMOKEGRENADE_YELLOW
M18SMOKEGRENADE_PURPLE
M18SMOKEGRENADE_WHITE
M67GRENADE
FLASHGRENADE
TWP_MK2_GRENADE
TWP_ZARYA3_STUNGRENADE
TWP_TENNISBALL_GRENADE

AMMO

ALL LOOSE AMMO

**Comment by SargeD** [comment]
SOME OTHER ODD ITEMS

HDSN_DETONATOR
HDSN_C4STICKS
HDSN_C4STICK
HDSN_CHARCOAL
HDSN_SULFUR
HDSN_GUNPOWDER
CARLOCKPICK
MASSBINOCS

MVS GEAR

MVS_BALACLAVA_SNOW
MVS_S10RESPIRATOR_SNOW
MVS_MEDICALPOUCH_TAN
MVS_ADMINPOUCH_OD
MVS_PACK_BLACK
MVS_SHROUD_OD
MVS_SHROUD_TAN
MVS_SHROUD_BLACK

**Comment by BnYrB** [comment]
I would be interested in bringing all the clothing back TBH, but time is the only problem. Would you interested in making these updates? 

The public branch can be used do make a local test server.

**Comment by SargeD** [comment]
I'm up for it. I'll need your help getting spooled back up. Been away from it for awhile so I'm a bit rusty and need some clarification on what repositories we are pulling from.

**Comment by SargeD** [comment]
This is done
