### ISSUE TITLE
Bugged airdrop

### ISSUE THREAD

**Issue by Sharkparty65** [42MonthsAfter/42MonthsAfter-Public#471]
Airdrop in East Harbor landed on top of roof. Looks inaccessible and also spawned no loot

![20220609205341_1](https://user-images.githubusercontent.com/96384465/172969009-8dc9a642-06ad-4dd2-9eb1-ce78ee831db4.jpg)

**Comment by BnYrB** [comment]
Fixed. Tightened up the drop radius so it shouldn't hit any buildings. May still hit trees, avoidance isn't great. 

If something lands on a roof or in a tree, check the ground under / around it and you will probably find the loot still.
