### ISSUE TITLE
candy not selling

### ISSUE THREAD

**Issue by Joshuabab** [42MonthsAfter/42MonthsAfter-Public#472]
not sure if this is a bug or intentional but the suspicious candy doesn't sell to the drug trader

**Comment by Joshuabab** [comment]
suspicious blue candy*

**Comment by BnYrB** [comment]
So this is part of mass items which haven't been added to the traders yet. Will be added when the rest of the items are added. See ticket #452 Add Mass Items to Trader.

Closing because duplicative.
