### ISSUE TITLE
Leader Board

### ISSUE THREAD

**Issue by SargeD** [42MonthsAfter/42MonthsAfter-Public#476]
Every time I try to check the Leaderboard by holding "B" the game crashes.

**Comment by SargeD** [comment]
This is a confirmed issue with the mod. Its being reported to the mod creator.

**Comment by BnYrB** [comment]
Still broken!

**Comment by BnYrB** [comment]
Closing this out as it's a known bug and is listed in the discord channel. Will keep an eye out for a mod update to see if it gets a fix.
