### ISSUE TITLE
coonan mag

### ISSUE THREAD

**Issue by Joshuabab** [42MonthsAfter/42MonthsAfter-Public#477]
the coonan 357 mag doesn't seem to work with the gun it's for

**Comment by BnYrB** [comment]
Will report to the mod creator, not much else we can do beyond that sadly. Will test and if it's completely broke I'll remove it from the world until it's fixed.

**Comment by BnYrB** [comment]
@SargeD Was this fixed with your latest updates by chance?

**Comment by SargeD** [comment]
Fixed. There were 2 different mags in the trader. The correct one is in the types, so no issue there.
