### ISSUE TITLE
Casino Chips & Electronic repair kit

### ISSUE THREAD

**Issue by Raider2-1** [42MonthsAfter/42MonthsAfter-Public#487]
Cant sell my casino chips in the money exchange (582 chips)

Buying a electronic repair kit gives a kit with 1%

**Comment by BnYrB** [comment]
Adding to the next update for fixes.

**Comment by SargeD** [comment]
I fixed the electronic repair kit with the Big Trader Fix

**Comment by SargeD** [comment]
I think this is complete, since you sell your chips through the inventory.
