### ISSUE TITLE
BBP Land Claim does not disable construction

### ISSUE THREAD

**Issue by shaunhardy** [42MonthsAfter/42MonthsAfter-Public#488]
The Land Claim flag pole gives the option to enable/disable construction, however toggling this seems to have no effect. I am still able to construct walls, etc.

**Comment by BnYrB** [comment]
I believe this is a known bug, I'll check with the creators discord and get back to you.

**Comment by BnYrB** [comment]
This is a known bug, can confirm. We will get the update when BBP updates with the fix. Nothing we can do until then but put it in "known bugs" in discord and keep an eye on it.
