### ISSUE TITLE
Raiding Report

### ISSUE THREAD

**Issue by Raider2-1** [42MonthsAfter/42MonthsAfter-Public#490]
As it currently stands, Heavy Breaching Charges and Homemade Breaching Charges can only be placed on Vanilla items (Gates, Walls, Watchtowers etc) 
The Door Barricades and the BBP items can not have charges placed on them.

**Comment by BnYrB** [comment]
Appreciate you guys taking the time to do this. I think we have a pretty nice balance right now.   What do you think?

**Comment by BnYrB** [comment]
Going to close this out and move it to the discord forum channel
