### ISSUE TITLE
Garden lime sold at vendor is empty

### ISSUE THREAD

**Issue by shaunhardy** [42MonthsAfter/42MonthsAfter-Public#497]
![Empty bag](https://i.gyazo.com/c32ddfc51300621941010b21f9257f81.png)
The garden lime is empty when purchase from the vendor.

Also, the vendor will sell you any number of garden lime bags, but only one will appear in your inventory.

**Comment by BnYrB** [comment]
@SargeD would you mind taking a look at this the next time you're working on the trader?

**Comment by SargeD** [comment]
Done
