### ISSUE TITLE
Add Easter Eggs and other special items to BM trader

### ISSUE THREAD

**Issue by BnYrB** [42MonthsAfter/42MonthsAfter-Public#503]
Would be awesome to get all the special items listed at the black market trader. I'm thinking those special items are:

- [ ] Masks, from mask mod and other mod packs like the covid masks from TWP
- [ ] Easter eggs from mung and msp packs
- [ ] Maybe some of the MSP special melee items?

Anything else you think would be good to add there?

**Comment by SargeD** [comment]
This is pretty easy, I added them already to the trader file, just have to create a category

**Comment by SargeD** [comment]
Added Masks, Band Shirts, Eggs, Cat and bunny ears and a few other Items. Not going to close this since there are probably other Items we will want to add later.
