### ISSUE TITLE
Add partial vehicles to community online tools

### ISSUE THREAD

**Issue by BnYrB** [42MonthsAfter/42MonthsAfter-Public#506]
All the vehicles are set to spawn with 100% parts, we need to make a version of each that is missing / has different parts so that it can be placed, found and then assembled by the user. 

This will help with admin placement of items for events, etc

**Comment by SargeD** [comment]
I can do this

**Comment by SargeD** [comment]
ok so the cfspawnabletypes file DOES NOT have all the parts spawning in on vehicles. There is some cleaning up and additions we can add to this but they aren't spawning in complete, according to this file.

**Comment by SargeD** [comment]
Done
