### ISSUE TITLE
Balance Weed Economy

### ISSUE THREAD

**Issue by BnYrB** [42MonthsAfter/42MonthsAfter-Public#516]
Stills feels off, need to look at seed count vs grow times vs ducttape prices, etc to see how much we can make this feel super balanced.

**Comment by SargeD** [comment]
I did this before, but we had the weed at different levels, like skunk was the low and Blue God was the High. I can do that again or we can make them all the same. Let me know

**Comment by SargeD** [comment]
ok so I recalculated them, put them in this order from lowest to highest - Skunk, Nomad, S1, Stardawg, Blue, Kush, Future and BlackFrost.

**Comment by shaunhardy** [comment]
If interested, here's a breakdown of cost and profit for cannabis as it stands right now.

#### Investment:
  $2000 (2x seed packs, 4x seeds per pack) per greenhouse
  ?? (1/2? garden lime) per greenhouse
  3 hours grow time
  3 minutes processing time per greenhouse

#### Returns:
  Max 64 buds (2 bricks)
  $7,200 (2 bricks @ $3600/ea) per greenhouse

#### ROI:
  $5,200 ($7,200 - $2000) per greenhouse
  360% ROI

#### Profit:
  1 greenhouse  = $5,200 ($2,360/hr)
  8 greenhouses = $41,600 ($13,866/hr)

**Comment by BnYrB** [comment]
Pushed to production
