### ISSUE TITLE
Update Trader for New Cars

### ISSUE THREAD

**Issue by BnYrB** [42MonthsAfter/42MonthsAfter-Public#524]
Since all cars will be able to be purchased and only found in world at events, we need to look to break the cars down by different categories sine there are so many of them.

We need to look to price them accordingly too, from cheapest to like freaking impossible. 

Here is a full list of the vehicles and all their parts:

**Comment by BnYrB** [comment]
[TraderVehicleParts.md](https://github.com/42MonthsAfter/42MonthsAfter-Public/files/9390817/TraderVehicleParts.md)

**Comment by BnYrB** [comment]
The mod creator who made the vehicle pack supplied this as a starting place for the trader:

[TraderPlusPriceConfig(not finished yet).md](https://github.com/42MonthsAfter/42MonthsAfter-Public/files/9390832/TraderPlusPriceConfig.not.finished.yet.md)

**Comment by SargeD** [comment]
I know you said you were starting on this so I don't want to do anything until we talk about it so we aren't stepping on each other

**Comment by BnYrB** [comment]
You are good to go man, if you want to use my branch go for it.
