### ISSUE TITLE
Bugged Weed Plants

### ISSUE THREAD

**Issue by Crunch2009** [42MonthsAfter/42MonthsAfter-Public#530]
Just had 3 weed plants not produce any buds. They should have produced 8 and provided none

**Comment by BnYrB** [comment]
What strain was it?

**Comment by Crunch2009** [comment]
So, we found that for some reason I harvested them, and they went down to a different set of plants that were already harvested by Shaun

**Comment by BnYrB** [comment]
So no bug? 

And the buds themselves instead of dropping to the ground, jumped to a near by plant that had open spots because it was already harvested? Want to put a bug in on the mod creator page and make sure Im getting it right.

**Comment by SargeD** [comment]
When you harvest, the buds drops on the ground, DayZ being DayZ, sometimes they fall through the ground, drop in weird areas or just don't produce. I've had all three things happen before, but none of those happen all the time, so I don't think there is a bug.
