### ISSUE TITLE
Cabin doors invisible wall

### ISSUE THREAD

**Issue by PartyBear666** [42MonthsAfter/42MonthsAfter-Public#531]
There seems to be an invisible wall in the doorway of the cabin and not allowing entry or exiting. Started 8/30

**Comment by BnYrB** [comment]
Got this fixed, but I'm not sure exactly what was going on.  I destroyed the existing Build Fortification mod door and codelock to start from scratch, that + the server restart seemed to fix it. Will keep an eye out.
