### ISSUE TITLE
Missing Ammo from Trader

### ISSUE THREAD

**Issue by Crunch2009** [42MonthsAfter/42MonthsAfter-Public#541]
Hey Bunker, just wanted to let you know that you cannot buy 50BMG or the ammo ammo_408Cheytec at the Hollar

**Comment by Crunch2009** [comment]
You also cannot buy the other version of the M24 mags either. Just FYI

**Comment by BnYrB** [comment]
So the M24 is a teddy weapon pack mod gun that mags can only be bought at the black market trader. I need to get the TWP mod ammo added to the Holler, but that's going to take a minute. In the mean time I added boxes of 408 and 50 bmg. Will go in with the restart. 

Make sure you buy the right one!
