### ISSUE TITLE
M14 mags missing from trader

### ISSUE THREAD

**Issue by Sharkparty65** [42MonthsAfter/42MonthsAfter-Public#549]
^

**Comment by BnYrB** [comment]
Will add with the other midnight updates tonight

**Comment by BnYrB** [comment]
So the M14 is a teddysweapon mod gun, you can tell by the description being in half german / half english. These are the guns and mags that are only sold at the Black Market Trader. They are listed there for sale and I confirmed they are available.

**Comment by BnYrB** [comment]
Let me know if you have any questions!
