### ISSUE TITLE
Item Drop bug!

### ISSUE THREAD

**Issue by FakeNewsIntel** [42MonthsAfter/42MonthsAfter-Public#550]
if you drop something or die near something like a tree or wall, it does not show up in vicinity or hardly even pick it up.

**Comment by BnYrB** [comment]
Dropping items on hills or near objects will result in that at times. Like dying on a steep hill, the body tries to lay flat so part of it will be under the map. If you're lucky, your feet are under the map or under the object like the wall. This is just DayZ + a custom map, nothing we can do about it.
