### ISSUE TITLE
No Mini 14 Magazine

### ISSUE THREAD

**Issue by FakeNewsIntel** [42MonthsAfter/42MonthsAfter-Public#551]

**Comment by BnYrB** [comment]
Will get this updated tonight with the midnight restart

**Comment by BnYrB** [comment]
So the mod creator didn't add the mag in their file! It's missing completely from the PBO. I'm going to remove from the game until this is fixed, but we have no control over when that will be. Will put a bug report in on Mass's workshop page to let him know. 

Good find and thanks for reporting!

**Comment by BnYrB** [comment]
I stand corrected!!!! This uses the standard 5.556 mags from vanilla. Sorry for the confusion! This will remain in the game.
