### ISSUE TITLE
Storage NPC

### ISSUE THREAD

**Issue by ZombieTickler** [42MonthsAfter/42MonthsAfter-Public#553]
Hi, Tried selling a car battery to Storage NPC, would sell it nut not take it off me, i know its only 1$ but a hella dedicated person could sit there and make bank

**Comment by ZombieTickler** [comment]
Seems to be the same with the Truck Battery. Not sure if this will portray to the normal trader, where money will be given, but no battery sold

**Comment by ZombieTickler** [comment]
Just checked. Doesnt work at the normal trader :)

**Comment by BnYrB** [comment]
Will update this over the weekend, it sounds like it is selling a single usage instead of the entire item. should be a quick fix

**Comment by BnYrB** [comment]
Just pushed this fix, will go into place at the 6 pm EST restart. Please comment back here if you have any additional issues
