### ISSUE TITLE
Cure

### ISSUE THREAD

**Issue by MaxCaliber** [42MonthsAfter/42MonthsAfter-Public#570]
Spent 8,000 on a cure since the tetra and vitamins was not working. Still sick. Bought the equipment to make a cure and the microscope doesn't work

**Comment by BnYrB** [comment]
Could you expand more? Does the cure not spawn? Do you not get the prompt to make it when you combine everything?

Did you use your "clean" blood or "infected" blood?

**Comment by BnYrB** [comment]
@MaxCaliber Friendly ping for more details

**Comment by BnYrB** [comment]
Friendly ping @MaxCaliber

**Comment by MaxCaliber** [comment]
I used my clean blood and a brain, since that is what it originally said. The video said guts, so I may try that. I did not get a prompt with everything combined, but it may be guts instead of brain. Will test and retry

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MaxCaliber** [comment]
Tried it with my contaminated blood and zombie guts. Won’t let you use the guts in the microscope, only the brain. Still didn’t prompt anything after it was all put together.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by MaxCaliber** [comment]
Ok. Take care man, I mean that. Thanks for everything

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
