### ISSUE TITLE
Another crash, another death

### ISSUE THREAD

**Issue by MaxCaliber** [42MonthsAfter/42MonthsAfter-Public#572]
No clue what happened. Was able to actually drive my Gaz, update for vehicles seemed to work. Driving along, did not see anything in the road. Game stopped my vehicle and bugged me out, then crashed. Had to respawn, went back and could not see my vehicle. Died again, and a server restart took place.

**Comment by Crunch2009** [comment]
Same thing happened to us. We lost everything we had in that crash
