### ISSUE TITLE
Party Invites

### ISSUE THREAD

**Issue by ZombieTickler** [42MonthsAfter/42MonthsAfter-Public#574]
Party Invites are not working - im not sure if its a server side thing or just needing a reset but sometimes it works and then others the party screen doesnt.

**Comment by BnYrB** [comment]
Just tested, appear to be working fine. Are you saying when you hit "p" it doesn't load the screen?

**Comment by ZombieTickler** [comment]
Hi. It started working after reset but I hit P and it loads the screen but then sometimes its Blank down the people online section. I know there are people online because who I play with he had the same issue and we were both on for sure.

I'll reply to thread with a screenshot if it does it again.
